### ISSUE TITLE
out in return tuple yields syntax error with wrong line number

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#1025]
When converting the out parameters to return tuples in the operations test, I put an "out" in a return tuple and got an unhelpful error message:
```
/Users/bernard/builds/ice/csharp/test/Ice/operations/Test.ice(161): error : syntax error [/Users/bernard/builds/ice/csharp/test/Ice/operations/msbuild/client/client.csproj]
/Users/bernard/builds/ice/csharp/test/Ice/operations/Test.ice(161): error :  [/Users/bernard/builds/ice/csharp/test/Ice/operations/msbuild/client/client.csproj]

```

The offending operation is also on line 162, not 161:
```
(LongSS r1, ShortSS r2, IntSS r3, out LongSS r4) opShortIntLongSS(ShortSS p1, IntSS p2, LongSS p3);
```

**Comment by InsertCreativityHere** [comment]
Fixed in #1032 (mostly).
Now there's a dedicated error message for when the out qualifier is used in return tuples:
`return members cannot be marked as out`

The line numbers not matching up with syntax errors is a known issue, and is due to the way that MCPP passes input to the parser. Once we replace MCPP with our own Bison based preprocessor, this should no longer be an issue.
