### ISSUE TITLE
ZeroC not working with Angular

### ISSUE THREAD

**Issue by sergiocapozzi77** [zeroc-ice/ice#1039]
Hi,

I was trying to use ICE in my Angular 10 application.
I've installed the ice package with npm and simply called Ice.initialise() but I receive the following error:

```
ModuleRegistry.js:25 Uncaught TypeError: m.require is not a function
at ModuleRegistry.js:25
at Array.forEach (<anonymous>)
at Function.require (ModuleRegistry.js:23)
at Object.<anonymous> (Ice.js:7)
at Object../node_modules/ice/src/Ice/Ice.js (Ice.js:45)
at __webpack_require__ (bootstrap:79)
at Object../node_modules/ice/src/index.js (index.js:5)
at __webpack_require__ (bootstrap:79)
at Module../src/app/app.component.ts (main.js:109)
at __webpack_require__ (bootstrap:79)
```

Steps to repro:
- create a new Angular app with: ng new my-app
- install ice: npm install ice
- call Ice.initialize() from inside a module (i.e. app.component.ts)

Sample attached:
[test-ice.zip](https://github.com/zeroc-ice/ice/files/5230646/test-ice.zip)

**Comment by pepone** [comment]
I got this working with a few changes to your setup

First I update the project to include the browser version of Ice library. Then I update the build to use a custom webpack configuration, this requires `@angular-builders/custom-webpack`. In the custom webpack configuration set ice as an external module so that the imports not result in build the node version.

I attached a modified version of test-ice.zip with the above changes, let me know if you need more help with this.

[test-ice.zip](https://github.com/zeroc-ice/ice/files/5231329/test-ice.zip)

**Comment by sergiocapozzi77** [comment]
Thanks! That worked

**Comment by sergiocapozzi77** [comment]
Any idea how to fix also the unit test runner? I've got the same issue.
run "ng test" to see the issue.

I've tried to add the custom-webpack to karma as well....but didn't work.

**Comment by sergiocapozzi77** [comment]
Nevermind...my fault. I forgot to add the script 
Here is the correct settings:
"test": {
          "builder": "@angular-builders/custom-webpack:karma",
          .....
            "scripts": [
              "node_modules/ice/lib/Ice.js"
            ],
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            }
