### ISSUE TITLE
Invalid certificate error while running unit tests

### ISSUE THREAD

**Issue by mfronczyk** [zeroc-ice/ice#1108]
I get a couple of errors about invalid SSL certificates when running C++ unit tests in ICE 3.5.1. Might the reason be that the certificates used by test servers are old and need to be updated or it's something wrong with my setup?

Could you let me know where the certificates for tests are specified?

**Comment by pepone** [comment]
You should 3.7.4, the 3.5.1 release is quite old,  the certificates are in certs top-level directory https://github.com/zeroc-ice/ice/tree/3.5/certs

**Comment by mfronczyk** [comment]
Thanks. Yes we know, but we aren't ready yet.

So I should just run the makecerts.py with appropriate arguments, right? I see that for newer versions there's some documentation provided on that.

**Comment by pepone** [comment]
try `makecerts.py -f`, you can also try with the certificates from the 3.7 branch, they might work depending on your OpenSSL version.

**Comment by mfronczyk** [comment]
OK, thank you!

I'm linking with openssl 1.0.2o, do you maybe know off hand if certs from 3.7 would work?

**Comment by pepone** [comment]
> I'm linking with openssl 1.0.2o, do you maybe know off hand if certs from 3.7 would work?

They should most probably work, we support 1.0.0 or later with 3.7

**Comment by karkucha** [comment]
Hi, 
I'm working together with mfonczyk on this issue. We couldn't use certs from newer ICE. because 3.5 is the last version that has
dependency to OpenSSL on Windows. 
Running `makecerts.py -f` solved some problems with certificates. Thanks for the suggestion!
Unfortunately, _cpp\test\IceSSL\configuration_ is still failing on _testing certificate verification_ with following error message: 
_testing certificate verification... failed!
 AllTests.cpp:406: assertion 'false' failed
10/22/20 18:04:53.701 warning: connection exception:
TcpTransceiver.cpp:469: Ice::ConnectionLostException:
connection lost: The specified network name is no longer available.
local address = 127.0.0.1:12010 
remote address = 127.0.0.1:54430 
10/22/20 18:04:53.702 warning: connection exception: TcpTransceiver.cpp:469: Ice::ConnectionLostException:
connection lost: The specified network name is no longer available. 
local address = 127.0.0.1:12010
remote address = 127.0.0.1:54445_
I get a very similar error in \cpp\test\Freeze\evictor_. 
Could you please advise me on how should I proceed with such errors?

**Comment by pepone** [comment]
>I'm working together with mfonczyk on this issue. We couldn't use certs from newer ICE. because 3.5 is the last version that has
>dependency to OpenSSL on Windows.
Not sure what you mean,

> Unfortunately, cpp\test\IceSSL\configuration is still failing 

`cpp\test\IceSSL\configuration` uses its onw set of certficates in `cpp\test\IceSSL\certs` there is a makecerts script there too https://github.com/zeroc-ice/ice/tree/3.5/cpp/test/IceSSL/certs 

> I get a very similar error in \cpp\test\Freeze\evictor

The Freeze\evictor test doesn't use OpenSSL, maybe is a different one?

**Comment by pepone** [comment]
> Just before that, I get the following Windows pop-up:

That is expected when a test hits an assert, for IceSSL/configuration it is cleary because you didn't update its certificates, for Freeze/evictor you can click Debug and see where it is failing. If you are not using Freeze you might as well skip this test.

**Comment by karkucha** [comment]
pepone, thanks for your help. Updating certificates for IceSSL solved the issue. Our application doesn't use Freeze, so I'll skip it.
Thanks!

**Comment by pepone** [comment]
Glad you get it working, I will close this issue now.
