### ISSUE TITLE
Can the client's thread pool be isolated between each service？

### ISSUE THREAD

**Issue by wei804378140** [zeroc-ice/ice#1152]
It is understood that the server can configure a separate thread for each adapter, but the client seems to be unable to.Can the client's thread pool be isolated between each service?

**Comment by bentoi** [comment]
An Ice communicator only supports a single client thread pool. You need to create multiple communicators if for some reasons you need multiple client thread pools. Needing multiple client thread pools is quite unusual. Why do you need this?

**Comment by wei804378140** [comment]
Because the thread pool is not isolated, when a service becomes slow, the client thread pool will be full, thus affecting the calls of other services.

**Comment by bentoi** [comment]
Are you using asynchronous message invocation (AMI)? 

The client thread pool will only run out of threads if your client actually keeps these threads busy from the implementation of your AMI callbacks. To prevent the client thread pool running out of threads, if your AMI callback need to perform long running operations, I recommend to instead perform the long running operations on a custom thread pool from separate threads.

**Comment by wei804378140** [comment]
Hello，Is the Ice.BackgroundLocatorCacheUpdates parameter truly asynchronous?

**Comment by bernardnormier** [comment]
If you use asynchronous invocations, the invocations are 100% asynchronous and won't block the calling thread.

The property [Ice.BackgroundLocatorCacheUpdates](https://doc.zeroc.com/ice/3.7/property-reference/miscellaneous-ice-properties#id-.MiscellaneousIce.*Propertiesv3.7-Ice.BackgroundLocatorCacheUpdates) is about a detail of the invocation implementation and does not make an async invocation more or less asynchronous.

When you invoke on an indirect proxy, Ice needs to "resolve" this indirect proxy - find the actual target endpoint to connect to. If it's not the first time you use this proxy, the connection is by default cached in the proxy so the invocation just uses this cached connection. But if it's the first time you use this proxy, Ice resolves this indirect proxy with its configured Locator (typically provided by a remote IceGrid registry server or a local IceDiscovery), and then caches the result of this resolution in its own locator cache (it caches only successful results).

`BackgroundLocatorCacheUpdates` allows you to tell Ice to use stale entries in the locator cache, instead of waiting (asynchronously) for resolution when the entry in the locator cache is stale.
Note that an entry in the locator cache can become stale only when you configure a locator cache timeout (see for example [Ice.Default.LocatorCacheTimeout](https://doc.zeroc.com/ice/3.7/property-reference/ice-default#id-.Ice.Default.*v3.7-Ice.Default.LocatorCacheTimeout). By default, the timeout is infinite so entries never become stale.
