### ISSUE TITLE
AMI call never completed

### ISSUE THREAD

**Issue by xorian** [zeroc-ice/ice#1200]
**Version(please complete the following information):**
 - Ice Version 3.6.4
 - OS: Linux
 - Distribution: CentOS

**Describe the bug**
After switching a collection of RPC call sites from synchronous to AMI I observed an instance where the callee received and processed a call, but on the caller side neither the completion callback nor the exception callback was ever called and the Ice::AsyncResultPtr object's "isCompleted" member function continues to return false.

**Expected behavior**
The completion callback or the exception callback should be executed on the caller side and the Ice::AsyncResultPtr object's state should change so that "isCompleted" returns true.

**Additional context**
This is in a distributed application written in C++ for which I've been using ICE for a little over 5 years.  The connections are all TCP without SSL.  I'm guessing that this might be some sort of race condition as I've seen only a handful of these in testing after switching a collection of calls to AMI.  Unfortunately I don't have an easy way to reproduce the problem.  Debug logging in my test infrastructure shows me that the call is processed on the callee side, but the result somehow never arrives back at the caller.  I have no idea whether the problem is on the sending side or the receiving side.  (The callee side is using AMD, but has been since before I saw this problem.)  If any known bugs like this have been fixed in 3.7 I'll be happy to upgrade, but I haven't been able to find other similar problem reports.

**Comment by bentoi** [comment]
With AMI, Ice is not only calling your servants anymore, it also calls your asynchronous message invocation callbacks and it uses the Ice client thread pool for this purpose. And the issue you describe is very often caused by thread starvation of the Ice client thread pool. Typically, one of the AMI callback holds on the Ice client thread preventing other responses from being processed. 

Can you attach to the process with the debugger when this happens to get the state of the process threads? This should give us a clue on why your application doesn't release the Ice client thread pool threads. Increasing the size of the Ice client thread pool might also help but if there's a deadlock in your AMI code it will only delay the problem. So it's important that you understand why it hangs in the first place and the best way to figure this out is to check the state of the threads when the hang occurs.

**Comment by xorian** [comment]
I was able to get a look at the failure in the debugger, and it turns out that it was a mistake in my code that caused a different AMI callback to deadlock (consuming the single client thread and preventing the incomplete AMI call's callback ever being called).  Thanks very much for the help (your description of no client threads being available was definitely the key), and apologies for opening an issue that I should have solved myself.
