### ISSUE TITLE
createObjectAdapterWithEndpoints not supported in Javascript

### ISSUE THREAD

**Issue by daveoon** [zeroc-ice/ice#194]
I need to create a callback and require to createObjectAdapterWithEndpoints in order to receive the callback. createObjectAdapter() is not working at all. I check the source code the method is there but it complains "::Ice::FeatureNotSupportedException". 

Is there something im not doing correct or is this a bug?

**Comment by pepone** [comment]
The server side support for JavaScript is limited to bidirectional connections, see this for a list of the features supported with the JavaScript mapping https://doc.zeroc.com/ice/3.7/language-mappings/javascript-mapping

The Ice/bidir demo shows how to use callbacks over a bidirectional connection with Ice for JavaScript

https://github.com/zeroc-ice/ice-demos/blob/27c4c8491d6951867e48b13e1547204c683dcbcc/js/Ice/bidir/Client.js#L41-L58

**Comment by daveoon** [comment]
Thank you.

I started with the demo, but for my case, my interface was from another proxy interface to add the callback. i tested with Java and its working using createObjectAdapterWithEndpoints() follow by adapter.activate(). However, the same flow does not work on JS code.

**Comment by pepone** [comment]
> I started with the demo, but for my case, my interface was from another proxy interface to add the callback

Can you clarify what you are trying to do? you can add any callback to an adapter when using a bidirectional connection, it is still a regular adapter but rather than accepting connections on an endpoint it reuses and open connection.

You can read more about bidirectional connections in the manual https://doc.zeroc.com/ice/latest/client-server-features/connection-management/bidirectional-connections

**Comment by daveoon** [comment]
Yes, I have look into the article on bidirectional connections and understand the concept pretty much.

I am actually working on Murmur.ice where it only published one 'Meta' endpoint which I get proxy from `communicator.stringToProxy('Meta -e 1.0:tcp -h 127.0.0.1 -p 6502')`. I need to add the callback at `Server::addCallback(ServerCallback *)` where the tricky part now is the Server interface is obtain from `meta.getServer(1)` and invoke `server.addCallback(cb)`. I manage to get Java working only after i use the createObjectAdapterWithEndpoints method.

I also realise the server did manage to add the callback, however it failed to callback due to empty IP.
Add JS Callback to server logged:
```
<W>2018-09-04 17:29:44.380 1 => Added Ice ServerCallback c36b4fc6-c360-4aa9-83ca-29aac5d1d3d8 -o
```
Add Java Callback to server logged:
```
<W>2018-09-04 17:30:04.539 1 => Added Ice ServerCallback dc72438b-32ff-43db-bfb0-01693f85a6c2 -o:tcp -h 127.0.0.1 -p 64347 -t 60000
```

You can the logged statement that one ends with the tcp endpoint while the other is empty.

**Comment by pepone** [comment]
I see you can use a fixed proxy this way, you will be able to solve this by using Glacier2 see https://doc.zeroc.com/ice/latest/ice-services/glacier2/callbacks-through-glacier2

**Comment by daveoon** [comment]
@pepone Thank you very much! I will take a look and this should be helpful. @

**Comment by daveoon** [comment]
@pepone not able to get glacier2 working yet. may i know whar do you mean by fixed proxy? in any case, i used creatObjectAdapterWithEndpoints work in java, is there something i did wrongly here?

**Comment by pepone** [comment]
For JavaScript you were using a fixed proxy, a fixed proxy doesn't have and endpoint  and is bound to a particular connection, the proxy received by the server will not be usable as is in this case, the server will have to call `ice_fixed` to create a new proxy that is bound to a connection before make invocations. 

For Java you are using a direct proxy and all is fine in this case, the server can just use the proxy as is.

You can read more about different proxy type in https://doc.zeroc.com/technical-articles/general-topics/the-fundamentals-of-proxies

**Comment by daveoon** [comment]
sorry im not able to edit the above comment on my iphone so i need to add it here. do you suggest for me to use java or python instead of javascript? it seems like there is still some shortfall. my idea is to have all my server side code with nodejs but seems like its not very promising. any advise will be greatly appreciated.

**Comment by bentoi** [comment]
As José mentioned, our JavaScript mapping currently doesn't support server-side endpoints. As a consequence, a JavaScript server can't listen on a TCP port for incoming connections. This restriction is fine when using JavaScript with web browsers since the web browser JavaScript runtime doesn't provide a way to accept network connections. But as you discovered, when using NodeJS to implement a server, this can be problematic.

For callbacks, Murmur requires to be able to establish a connection to the Ice process that provides the callback. So if this Ice process is a JavaScript NodeJS process, this indeed doesn't work since the NodeJS process can't listen on a TCP port.

A solution suggested by José would be to put Glacier2 between the Murmur server and your NodeJS process. This is however a bit more work as it requires your NodeJS process to establish a session with Glacier2 and talk to the Murmur server through Glacier2 (the Murmur server invocations on the callback will also go though Glacier2). If you are interested in this solution, we can provide some pointers.

Another option would be for the Murmur server to support bi-directional connections (the implementation of the Murmur server addCallback method would create a fixed proxy using ice_fixed). It does require few changes in the Murmur Ice server side code however.

On our side, there are 2 things we could do to improve this:
* support server-side endpoints (i.e.: the ability to accept TCP connections) with NodeJS
* make it possible to use bi-directional connection on the server side without server side changes

These are two things we considered doing in the past, we'll discuss them again.

**Comment by daveoon** [comment]
@bentoi thank you very much. for long run, i would prefer the glacier way or it will be even better if the suggested ways can be implemented. in the mean time, i will separate my logic to different codebase since they are actually of difference concerns.

Appreciate if you can provide some pointers for the Glacier2 solution?

**Comment by bentoi** [comment]
Checkout https://github.com/zeroc-ice/ice-demos/tree/3.7/js/Glacier2/simpleChat

This demo does exactly what you want. The JavaScript client creates a session with Glacier2 and setups a callback proxy with the chat server through Glacier2. The chat server invocations on the callback proxy go through Glacier2. Glacier2 forwards the requests over the bi-directional connection established by the NodeJS client.

With your application, the chat server will be the mumble server and the JS chat client will be your NodeJS server.

**Comment by daveoon** [comment]
@bentoi Thank you for the patience and explanation. Perhaps, Glacier is the way to go and will take some time to test it out. Have a good day! :)

**Comment by aikoven** [comment]
@daveoon You can avoid the complexity of dealing with Glacier2 by using custom `Ice.Router` implementation. Here's a gist with a small router written in Python:

https://gist.github.com/aikoven/0f088be07db32598c6389adedbdfa75f

**Comment by daveoon** [comment]
@aikoven i didn't look into the code in details but i saw router.py and server.py, do you need the server.py in order to work with router.py?

**Comment by aikoven** [comment]
There's `router.py` that you start in a separate process that binds to a TCP interface.
And then there's `server.js` that contains your Node.js server logic; it establishes a connection with the router that allows it to accept incoming requests.

**Comment by daveoon** [comment]
@aikoven hi, im getting the error below and can you advise how to implement getClientProxy?

```
NotImplementedError: servant method 'getClientProxy' not implemented

identity: SimpleRouter/router
facet: 
operation: getClientProxy
remote host: 127.0.0.1 remote port: 5880
```

**Comment by aikoven** [comment]
I've added the missing method, see https://gist.github.com/aikoven/0f088be07db32598c6389adedbdfa75f#file-router-py-L72
