### ISSUE TITLE
Add Service.h back to Ice.h

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#2204]
It's currently not included.

**Comment by pepone** [comment]
We removed `Service.h` from the `Ice.h` header because, at the time, it was the only header that pulled in `Windows.h` and required the Windows SDK.

With the new SSL APIs, we already include `Windows.h` from `Ice/SSL/Config.h`. Therefore, we should add `Service.h` back as it no longer introduces additional dependencies.
