### ISSUE TITLE
Cannot create two "" object adapters in Java

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2301]
This code incorrectly prevents the creation of two "" object adapters in Java:
https://github.com/zeroc-ice/ice/blob/56b6609b1803f3052d4e52da7ab3e6f863988f22/java/src/Ice/src/main/java/com/zeroc/IceInternal/ObjectAdapterFactory.java#L127

The equivalent C++ and C# code handles this situation differently.

**Comment by InsertCreativityHere** [comment]
I don't think this issue is correct, looking at the code, it looks like the code allows for multiple `""` adapters.
https://github.com/zeroc-ice/ice/blob/58d871634da19dc149266ac5c764a9c0ee68bf49/java/src/Ice/src/main/java/com/zeroc/IceInternal/ObjectAdapterFactory.java#L122-L128

Comparing this entire function to the C# equivalent: https://github.com/zeroc-ice/ice/blob/58d871634da19dc149266ac5c764a9c0ee68bf49/csharp/src/Ice/Internal/ObjectAdapterFactory.cs#L140-L148 I don't see any differences either. But it's always possible I'm missing something.

**Comment by bernardnormier** [comment]
Yes, the code seems correct. I should have included a test-case.
