### ISSUE TITLE
Better PropertyNames

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2746]
We use config/PropertyNames.xml and its associated Python script to define all Ice-reserved properties, and to generate supporting code in C++, C#, Java, and JavaScript.

For example:
```xml
<section name="Ice">
        <property name="AcceptClassCycles" default="0" />
        <property name="Admin" class="objectadapter" />
        <property name="Admin.DelayCreation" default="0" />
```

is the beginning of the Ice.* reserved properties.

I propose we make the following improvements:

- for each property, specify the language(s) to which is applies as cpp, cs, java, js or all
   the current behavior is "all", which does not make sense for many properties, especially in js

- generate helper code to parse ObjectAdapter properties
  we currently duplicate this logic / list of properties in the various ObjectAdapter implementations, which is error-prone.

**Comment by externl** [comment]
Starting to look at implementing this issues. I think having to specify `languges="..." for each property is a bit burdensome and makes the xml harder to read. All languages should be supported by default without an attribute. 

When we do need to limit the number of languages, I wonder if we should have an exclude list rather than an include list. 

```xml
<property name="Foo" default="100" languages="cpp,csharp,java" />
<property name="Bar" default="10" languages="cpp,csharp,java" />
...
```

vs 

```xml
<property name="Foo" default="100" exclude="js" />
<property name="Bar" default="10" exclude="js" />
...
```

Attribute name ideas: `exclude`, `exclude-language`, `exclude-from`. I like `exclude`, it's short and concise.

**Comment by externl** [comment]
After talking about it with @bernardnormier, I think it be inclusive as per the original proposal. There are lots of properties that are single language only, eg. Glacier2, IceGrid, etc.
