### ISSUE TITLE
Review deprecation warnings work as expected in C++

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2962]
We currently are not getting warnings with Clang and GCC when called proxy operations that are marked as deprecated in Slice.

I did some testing and we get the expected deprecated warnings if we comment out the pus/pop disable warnings in the generated headers.

**Comment by bernardnormier** [comment]
Fortunately the push/pop principle we use for deprecated is correct and works.

The issue is a bug in SlicedData.h, where we push an unrelated ignore warning _but_ forgot to pop it. It has a ripple effect since the next pop pops the wrong push. And the SlicedData.h conditionals are clang/gcc only, which explains why VC++ was not affected.

Lesson: make sure that any "push" has a matching "pop" in the same header.
