### ISSUE TITLE
Handling of deprecated in Slice library

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#3039]
The new Slice/deprecated test (see #3038) shows two issues in the Slice library (aka Slice parser).

- `getDeprecationReason` returns an empty string and not `nullopt` for Slice metadata `["deprecated"]`
-  when we define a Slice class or interface (Def) without an existing Decl, the deprecated metadata for the Def is not copied into the Decl created by the Parser

I think these two issues are related. It could be cleaner for the Parser to consume the deprecated Metadata and provide direct support for deprecated--and not keep it as a generic metadata to be consumed by the Slice compilers.

**Comment by InsertCreativityHere** [comment]
> `getDeprecationReason` returns an empty string and not `nullopt` for Slice metadata

We can definitely change it to return `nullopt` as you suggest. My original thinking was that returning empty string would be completely unambiguous (`nullopt` = no metadata, `""` = no message, otherwise there's a message). But in practice, being able to disambiguate between "no metadata" and "no message" seems useless.

> when we define a Slice class or interface (Def) without an existing Decl...

I'm not a super big fan of our `Def`-`Decl` system in general, but given the case you describe, how does this manifest into a problem? Generally we don't even generate code for the `Decl`s unless a user actually wrote a forward declaration.

> It could be cleaner for the Parser to consume the deprecated Metadata and provide direct support for deprecated

What would you see as the benefit of doing this? All of the languages should really be using the parser functions `isDeprecated` and `getDeprecationReason`, so none of them should really be interacting with the metadata directly.
