### ISSUE TITLE
FormatMessage arguments

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#355]
If Windows fails to load a plugin library you can end up with an error message such as:

```
c:\ice\cpp\src\ice\pluginmanageri.cpp:460: ::Ice::PluginInitializationException:
plug-in initialization failed: unable to load entry point `IceSSL:createIceSSL': %1 is not a valid Win32 application.
```

See https://stackoverflow.com/questions/43615129/why-is-1-rarely-substituted-in-1-is-not-a-valid-win32-application for information on this %1 and a possible solution to get it substituted with something more useful.

**Comment by bernardnormier** [comment]
The problem is we always call FormatMessage with FORMAT_MESSAGE_IGNORE_INSERTS:
https://github.com/zeroc-ice/ice/blob/3.7/cpp/src/IceUtil/StringUtil.cpp#L862

We probably should add a more custom processing of this error code that has an associated system-message-with-insert. The insert here would be the filename we're loading.

**Comment by pepone** [comment]
That or allow for passing optional args to `errorToString` and do not set  when receive optional args

**Comment by bernardnormier** [comment]
I think the best solution here (the DLL loading) is to prepend information to the error message, such as:
```
unable to load entry point `IceSSL:createIceSSL': LoadLibraryW on `foobar.dll' failed with `%1 is not a valid Win32 application'.
```

**Comment by bernardnormier** [comment]
Fixed as I suggested on Windows. On Linux/macOS, the system error message from dlerror already provides the library name/symbol name.
