### ISSUE TITLE
Review C# mapping for structs

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#382]
Ice for .NET supports two different mappings for Slice structures. By default, Slice structures map to C# structures if they (recursively) contain only value types. If a Slice structure (recursively) contains a string, proxy, class, sequence, or dictionary member, it maps to a C# class.

There is also `cs:class` metadata that allows to force the class mapping for a Slice struct.

For struct with class members, this is desirable as the unmarshaling of class data members can happen after the struct read has completed, in this case we will be patching the original and not the copy as struct are value types

```
self.s2 = Test.SmallStruct.ice_read(is_);
```

In the code above if the patching of class data members happens after `ice_read` returns, it will not patch s2 data members but the original struct created inside `ice_read`

But there is no reason to force the class mapping when the struct doesn't contains classes, we should keep the struct mapping for the rest of the cases.

User will still be able to map struct to classes by using `cs:class` metadata

**Comment by pepone** [comment]
Currently adding a default value causes the struct mapping to change from struct to class, maybe better make this explicit and require to add "cs:class" for struct with default values.

**Comment by bernardnormier** [comment]
I think the best is to map a Slice struct to a C# struct when all the Slice data members are basic types (int, long, double), string, enum, proxies or Slice struct mapped to C# struct. And to a C# class otherwise. (Proxies, like strings, are immutable reference types).

The default value for the Slice data members wouldn't change the mapping. When mapped to a C# struct, the default values could be simply ignored.
