### ISSUE TITLE
Slice2java missing XXXPrxHelper.java, XXXPrxHolder.java etc in files generation

### ISSUE THREAD

**Issue by hellomrsun** [zeroc-ice/ice#405]
Hi,

I've tried to generate Java files of provided sample "Printer.ice" [link](https://doc.zeroc.com/ice/3.7/hello-world-application/writing-a-slice-file) using Slice2java.exe of Ice 3.7.2
And I try to generate them with Ice 3.4.2.
But I've found that a lot of files are missing with Ice 3.7.2.

Could you explain why?
Thanks

Ice 3.7.2:
command:
![image](https://user-images.githubusercontent.com/23157401/56767540-47e90480-67ac-11e9-9d18-20c2649f119a.png)
generated files:
![image](https://user-images.githubusercontent.com/23157401/56767333-c3968180-67ab-11e9-9676-a9d1c4132877.png)

Ice 3.4.2:
command:
![image](https://user-images.githubusercontent.com/23157401/56767448-14a67580-67ac-11e9-97b1-cc4b02c8062a.png)
generated files:
![image](https://user-images.githubusercontent.com/23157401/56767367-da3cd880-67ab-11e9-8a9b-d69d660eb1d9.png)

Edit:
I've also tried to generate csharp files with slice2cs.exe in Ice 3.7.2, and it generates correctly the XXXPrxHelper etc.

**Comment by pepone** [comment]
Hi, 

Ice 3.7.2 includes two different Java mapping `java` and `java-compat` see https://doc.zeroc.com/ice/3.7/language-mappings/java-mapping/selecting-the-java-mapping

We provide a version of the printer demo for both mappings:

 * https://github.com/zeroc-ice/ice-demos/tree/3.7/java/Manual/printer
 * https://github.com/zeroc-ice/ice-demos/tree/3.7/java-compat/Manual/printer

There have been substantial changes since 3.4.2 so you better review the documentation and the demos, don't expect to have the same generated files with 3.7.2 and 3.4.2

**Comment by hellomrsun** [comment]
Thanks pepone for the information 

I've tried to use the --compat option, and it did generate a lot more files.

command:
> slice2java.exe --compat "..\ice\Printer.ice"

But there are still some differences.
![image](https://user-images.githubusercontent.com/23157401/56788147-ec943200-67fe-11e9-8f57-2af1c8c5a097.png)

As I need to migration my application from Ice 3.4.2 to 3.7.2, I think I'll try the --compat version files first.

Thanks,
