### ISSUE TITLE
Failure running IceGrid/replicaGroup in debian Buster

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#526]
```
testing Query::findAllReplicas... ok

testing replication with round-robin load balancing... failed!

test/IceGrid/replicaGroup/AllTests.cpp:267: assertion `obj->getReplicaIdAndShutdown() == "IceBox1.Service1.Service1"' failed



test in IceGrid/replicaGroup failed:
```

**Comment by bentoi** [comment]
For the record, Buster reallocated a dynamic port for one of the IceBox service OA right after it was no longer used by the previous server instance. The locator cache was returning the endpoint for the replica group and since it still worked, the request was going to the wrong service. I fixed the test to make sure we always retrieve the latest endpoints from the IceGrid.
