### ISSUE TITLE
Linking failures with Python 3.8

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#635]
Python 3.8 has removed `-lpython3.8` from `python3-config --ldflags`. See https://docs.python.org/dev/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

> To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.

Our build system also passes `-Wl,--no-undefined` so the build now fails.

We have two options:

1. Remove `-Wl,--no-undefined`
2. Use the `--embed` flag 

I don't think 2 makes much sense as we're not embedding Python.

**Comment by pepone** [comment]
My understanding is that python expect that exceptions doesn't link with libpython an so libpytho is now behind the new `--embed` flag that is intended for applications embeding python not for extensions.

https://github.com/zeroc-ice/ice/commit/b4dc6a8631992e2bb8775d4e1c49110547d58569

We have this fix for debian/ubuntu because dh complains that we were linking with libraries that were not required.

for building a python extension we should not be linking with Python, or using the `python-config --ldflags` we should check what settings are used by pip `setup.py` builds I think they get the settings from `sysconfig`
