### ISSUE TITLE
how could I get the message count of a specific topic on the ice storm?

### ISSUE THREAD

**Issue by angrysnail** [zeroc-ice/ice#779]
Now I face some trouble.
When the subscriber program quit abnormally, the publish program does not know the issue, so it still push message to ice storm.
The icestorm hold more and more memory of the server,  now I want to know the number of the messages.

**Comment by bentoi** [comment]
How do you setup the [quality of service](https://doc.zeroc.com/ice/3.7/ice-services/icestorm/icestorm-quality-of-service) for your subscriber?

If it's setup to retry indefinitely, you can limit the number of queued events with the [IceStorm QueueSizeMax property](https://doc.zeroc.com/ice/3.7/property-reference/icestorm-properties#id-.IceStormPropertiesv3.7-service.Send.QueueSizeMax).

The number of queued events is available using [IceStorm Metrics](https://doc.zeroc.com/ice/3.7/ice-services/icestorm/icestorm-metrics). If you deployed IceStorm with the IceGrid, you can view these metrics using the IceGrid GUI. Otherwise, you could write a small python script based on the [metrics demo](https://github.com/zeroc-ice/ice-demos/tree/3.7/python/Ice/metrics) to retrieve them.

Also, I encourage you to check out [DataStorm](https://zeroc.com/downloads/datastorm), a broker less publish/subscriber solution.
