### ISSUE TITLE
Forward declaration of sequences

### ISSUE THREAD

**Issue by S-Bohn** [zeroc-ice/ice#995]
Is it possible to forward declare sequences?

Given two slice files

```Slice
module X
{
	interface Bar;
	sequence<Bar*> BarPrxSeq;

	interface Foo {
		BarPrxSeq getBars();
	} 
}
```
```Slice
module X
{
	interface Bar;
	sequence<Bar*> BarPrxSeq;

	interface Bar {
		void doBar();
	}
}
```

We forward declare an interface and use a sequence of that interface. This works for generated C++ code (gets translated into `using BarPrxSeq = ::std::vector<::std::shared_ptr<BarPrx>>;`) but not for C# or TypeScript. Because in those languages the sequence generates helper classes (C#: `public sealed class BarPrxSeqHelper` and TypeScript: `class BarPrxSeqHelper`, `Slice.defineSequence(X, "BarPrxSeqHelper", "X.BarPrx", false);`) in both generated source files. Which fail at compile / runtime.

Is there a way to use sequences of forward declared instances?

**Comment by bernardnormier** [comment]
Only classes and interfaces can be forward declared. Here you are actually defining `BarPrxSeq` twice.

Since you're not using `BarPrxSeq` in your second file, you could just remove this definition. Assuming you need it in several files, then the solution is to define `BarPrxSeq` in a common include file.

For Ice 4.0, we plan to introduce anonymous sequences which would provide another solution. With anonymous sequences, your first Slice definitions would become:
```
module X
{
	interface Bar;

	interface Foo 
        {
	    sequence<Bar*> getBars();
	} 
}

```

Ice 4.0 will also support an optional/nullable syntax like C# and Swift so, you would actually write:

```
sequence<Bar> getBars(); // returns a sequence of non-null Bar proxies
sequence<Bar?> getBars(); // returns a sequence of nullable Bar proxies (equivalent to sequence<Bar*>)
```

**Comment by S-Bohn** [comment]
Thanks for the answer.

Seems like anonymous sequences is what we want – so i guess i will create a common include file for now.
